import { Patient, PatientId, ScenarioId } from './types';

export const patients: Patient[] = [
  {
    id: PatientId.TomasPerez,
    nameKey: 'dashboard.patientNameTomas',
    cardDescriptionKey: 'dashboard.patientDescTomas',
    avatarUrl: 'https://picsum.photos/seed/tomas-perez/100/100',
    voiceName: 'Charon',
    presentingProblemKey: 'tomas.presentingProblem',
    demographics: {
      titleKey: 'sidebar.demographics',
      ageKey: 'sidebar.age',
      ageValueKey: 'tomas.demographics.age',
      genderKey: 'sidebar.gender',
      genderValueKey: 'tomas.demographics.gender',
      occupationKey: 'sidebar.occupation',
      occupationValueKey: 'tomas.demographics.occupation',
      locationKey: 'sidebar.location',
      locationValueKey: 'tomas.demographics.location',
    },
    clinicalPresentationKey: 'tomas.clinicalPresentation',
    scenario: {
      id: ScenarioId.TomasExceptions,
      titleKey: 'tomas.scenarios.exceptions.title',
      descriptionKey: 'tomas.scenarios.exceptions.description',
      objectiveKey: 'tomas.scenarios.exceptions.objective',
      sessionContextKey: 'tomas.scenarios.exceptions.context',
    },
  },
  {
    id: PatientId.AntoniaFlores,
    nameKey: 'dashboard.patientNameAntonia',
    cardDescriptionKey: 'dashboard.patientDescAntonia',
    avatarUrl: 'https://picsum.photos/seed/antonia-flores/100/100',
    voiceName: 'Kore',
    presentingProblemKey: 'antonia.presentingProblem',
    demographics: {
      titleKey: 'sidebar.demographics',
      ageKey: 'sidebar.age',
      ageValueKey: 'antonia.demographics.age',
      genderKey: 'sidebar.gender',
      genderValueKey: 'antonia.demographics.gender',
      occupationKey: 'sidebar.occupation',
      occupationValueKey: 'antonia.demographics.occupation',
      locationKey: 'sidebar.location',
      locationValueKey: 'antonia.demographics.location',
    },
    clinicalPresentationKey: 'antonia.clinicalPresentation',
    scenario: {
        id: ScenarioId.AntoniaGoals,
        titleKey: 'antonia.scenarios.goals.title',
        descriptionKey: 'antonia.scenarios.goals.description',
        objectiveKey: 'antonia.scenarios.goals.objective',
        sessionContextKey: 'antonia.scenarios.goals.context',
    },
  },
  {
    id: PatientId.JacintaJimenez,
    nameKey: 'dashboard.patientNameJacinta',
    cardDescriptionKey: 'dashboard.patientDescJacinta',
    avatarUrl: 'https://picsum.photos/seed/jacinta-jimenez/100/100',
    voiceName: 'Puck',
    presentingProblemKey: 'jacinta.presentingProblem',
    demographics: {
      titleKey: 'sidebar.demographics',
      ageKey: 'sidebar.age',
      ageValueKey: 'jacinta.demographics.age',
      genderKey: 'sidebar.gender',
      genderValueKey: 'jacinta.demographics.gender',
      occupationKey: 'sidebar.occupation',
      occupationValueKey: 'jacinta.demographics.occupation',
      locationKey: 'sidebar.location',
      locationValueKey: 'jacinta.demographics.location',
    },
    clinicalPresentationKey: 'jacinta.clinicalPresentation',
    scenario: {
        id: ScenarioId.JacintaResources,
        titleKey: 'jacinta.scenarios.resources.title',
        descriptionKey: 'jacinta.scenarios.resources.description',
        objectiveKey: 'jacinta.scenarios.resources.objective',
        sessionContextKey: 'jacinta.scenarios.resources.context',
    },
  },
  {
    id: PatientId.MartinJara,
    nameKey: 'dashboard.patientNameMartin',
    cardDescriptionKey: 'dashboard.patientDescMartin',
    avatarUrl: 'https://picsum.photos/seed/martin-jara/100/100',
    voiceName: 'Charon',
    presentingProblemKey: 'martin.presentingProblem',
    demographics: {
      titleKey: 'sidebar.demographics',
      ageKey: 'sidebar.age',
      ageValueKey: 'martin.demographics.age',
      genderKey: 'sidebar.gender',
      genderValueKey: 'martin.demographics.gender',
      occupationKey: 'sidebar.occupation',
      occupationValueKey: 'martin.demographics.occupation',
      locationKey: 'sidebar.location',
      locationValueKey: 'martin.demographics.location',
    },
    clinicalPresentationKey: 'martin.clinicalPresentation',
    scenario: {
        id: ScenarioId.MartinRupture,
        titleKey: 'martin.scenarios.rupture.title',
        descriptionKey: 'martin.scenarios.rupture.description',
        objectiveKey: 'martin.scenarios.rupture.objective',
        sessionContextKey: 'martin.scenarios.rupture.context',
    },
  },
  {
    id: PatientId.DiegoSanchez,
    nameKey: 'dashboard.patientNameDiego',
    cardDescriptionKey: 'dashboard.patientDescDiego',
    avatarUrl: 'https://picsum.photos/seed/diego-sanchez/100/100',
    voiceName: 'Aoede',
    presentingProblemKey: 'diego.presentingProblem',
    demographics: {
      titleKey: 'sidebar.demographics',
      ageKey: 'sidebar.age',
      ageValueKey: 'diego.demographics.age',
      genderKey: 'sidebar.gender',
      genderValueKey: 'diego.demographics.gender',
      occupationKey: 'sidebar.occupation',
      occupationValueKey: 'diego.demographics.occupation',
      locationKey: 'sidebar.location',
      locationValueKey: 'diego.demographics.location',
    },
    clinicalPresentationKey: 'diego.clinicalPresentation',
    scenario: {
        id: ScenarioId.DiegoRelapse,
        titleKey: 'diego.scenarios.relapse.title',
        descriptionKey: 'diego.scenarios.relapse.description',
        objectiveKey: 'diego.scenarios.relapse.objective',
        sessionContextKey: 'diego.scenarios.relapse.context',
    },
  },
];


export const translations = {
  en: {
    loading: {
      text: "Loading simulation...",
    },
    sidebar: {
      title: "Patient Information",
      sessionContext: "Session Context",
      presentingProblem: "Presenting Problem",
      demographics: "Demographics",
      age: "Age",
      gender: "Gender",
      occupation: "Occupation",
      location: "Location",
      clinicalPresentation: "Clinical Presentation",
      interpersonalStyle: "Interpersonal Style",
      copingMechanisms: "Coping Mechanisms",
      hiddenConcern: "Hidden Concern (Therapist's View)",
    },
    patientCreator: {
      cardTitle: "Create Custom Scenario",
      cardDescription: "Design your own patient profile to practice specific therapeutic challenges.",
      wizardTitle: "Patient Creation Wizard",
      backToDashboard: "Back to Dashboard",
      next: "Next",
      back: "Back",
      startSession: "Start Session",
      randomize: "Randomize",
    
      step1Title: "1. Select Therapeutic Model",
      step1Description: "Choose the clinical framework you want to practice. This will define the AI's core behavior and challenges.",
      model_sfb: "Solution-Focused Brief",
      model_sfb_desc: "Patient focuses on problems, resistant to exploring exceptions.",
      model_cbt: "Cognitive Behavioral",
      model_cbt_desc: "Patient presents clear cognitive distortions (e.g., catastrophizing).",
      model_mi: "Motivational Interviewing",
      model_mi_desc: "Patient is ambivalent about change, highlighting pros and cons.",
    
      step2Title: "2. Define Patient Demographics",
      step2Description: "Establish the patient's background. These details will subtly influence their language and concerns.",
      gender: "Gender",
      gender_male: "Male",
      gender_female: "Female",
      "gender_non-binary": "Non-binary",
      age: "Age Range",
      "age_20-30": "20-30 years",
      "age_30-40": "30-40 years",
      "age_40-50": "40-50 years",
      "age_50+": "50+ years",
      ses: "Socioeconomic Context",
      ses_low: "Low",
      ses_middle: "Middle",
      ses_high: "High",
    
      step3Title: "3. Define Clinical Picture",
      step3Description: "Set the therapeutic challenge and the patient's initial disposition.",
      problems: "Presenting Problem(s) (Select up to 2)",
      problem_procrastination: "Procrastination",
      "problem_social-anxiety": "Social Anxiety",
      "problem_relationship-conflict": "Relationship Conflict",
      "problem_low-self-esteem": "Low Self-Esteem",
      problem_grief: "Grief",
      attitude: "Initial Attitude",
      attitude_cooperative: "Cooperative",
      "attitude_anxious-guarded": "Anxious / Guarded",
      "attitude_skeptical-resistant": "Skeptical / Resistant",
    
      step4Title: "4. Define Interpersonal Style",
      step4Description: "Choose the patient's typical way of relating to others. This will strongly influence the therapeutic relationship.",
      style_secure: "Secure",
      style_secure_desc: "Able to discuss relationships with balance and openness.",
      style_anxious: "Anxious / Preoccupied",
      style_anxious_desc: "Seeks reassurance, fears abandonment, may over-analyze interactions.",
      style_avoidant: "Avoidant / Dismissive",
      style_avoidant_desc: "Values independence highly, dismisses emotional needs, avoids intimacy.",
      style_disorganized: "Disorganized",
      style_disorganized_desc: "Contradictory behavior; desires closeness but also fears it, leading to instability.",

      step5Title: "5. Select Core Coping Mechanisms",
      step5Description: "Choose how the patient typically responds to stress or difficult emotions. (Select up to 2)",
      mechanism_avoidance: "Avoidance",
      mechanism_avoidance_desc: "Changes the subject or minimizes topics that cause discomfort.",
      mechanism_intellectualization: "Intellectualization",
      mechanism_intellectualization_desc: "Discusses emotions in a detached, analytical, or academic way.",
      mechanism_humor: "Humor / Deflection",
      mechanism_humor_desc: "Uses jokes or sarcasm to deflect from serious feelings or topics.",
      mechanism_externalizing: "Externalizing Blame",
      mechanism_externalizing_desc: "Attributes problems to other people or external circumstances.",

      step6Title: "6. Define Hidden Concern (Optional)",
      step6Description: "Add a topic the patient is hesitant to discuss. This trains your ability to build trust. The AI will guard this secret until sufficient rapport is built.",
      hiddenConcernLabel: "Patient's Secret",
      hiddenConcernPlaceholder: "e.g., Ashamed of being fired, worried about their drinking...",
      skip: "Skip this step",

      step7Title: "7. Review and Start",
      step7Description: "Confirm your selections below. The AI will generate a patient based on this profile.",
      summary_model: "Therapeutic Model",
      summary_gender: "Gender",
      summary_age: "Age Range",
      summary_ses: "Socioeconomic Status",
      summary_problems: "Presenting Problems",
      summary_attitude: "Initial Attitude",
      summary_style: "Interpersonal Style",
      summary_coping: "Coping Mechanisms",
      summary_hiddenConcern: "Hidden Concern",
    },
    tomas: {
      presentingProblem: "Patient reports feeling 'stuck' and frustrated by a pattern of abandoning personal projects shortly after starting them.",
      demographics: {
        age: "34 years",
        gender: "Male",
        occupation: "Computer Technician",
        location: "Ñuñoa, Santiago",
      },
      clinicalPresentation: "Procrastination and skepticism. Central belief ('I have no willpower'). Defense mechanism of 'Yes, but...'. He minimizes evidence of his own competence.",
      scenarios: {
        exceptions: {
          title: 'Remoralization via Exception Finding',
          description: "A classic brief therapy scenario focused on finding and amplifying moments of success to counter the patient's narrative of failure.",
          objective: "Guide Tomás to identify at least one concrete exception to his belief that 'nothing works out for him' and explore it in detail.",
          context: "Session 1 of 1. This is the patient's first encounter. He is skeptical about therapy. The primary goal is remoralization.",
        },
        resistance: {
          title: 'Managing Resistance',
          description: "A more challenging scenario where Tomás's skepticism is heightened, requiring advanced techniques to build rapport and bypass resistance.",
          objective: "Successfully navigate Tomás's 'Yes, but...' defense mechanism without entering a debate, and reframe one of his complaints into a potential area of strength.",
        }
      }
    },
    antonia: {
      presentingProblem: "Patient reports a sense of identity loss ('I want to be the old Anto again') associated with mild depressive symptoms (anhedonia, apathy) triggered by high academic demands.",
       demographics: {
        age: "20 years",
        gender: "Female",
        occupation: "Architecture Student, second year",
        location: "Las Condes, Santiago",
      },
      clinicalPresentation: "Good therapeutic alliance already established. Collaborative attitude. Expresses a desire to reconnect with past interests (drawing, friends) displaced by university pressure.",
      scenarios: {
        goals: {
            title: 'Goal Co-Construction',
            description: "A foundational scenario for practicing collaborative goal-setting with a cooperative but overwhelmed patient.",
            objective: "Co-construct with Antonia at least one small, concrete, and behavioral objective that connects her with her 'old self'.",
            context: "Session 4. A good therapeutic alliance is already established. The patient is collaborative. The primary goal is co-constructing a concrete objective.",
        },
        identity: {
            title: 'Strengthening Identity',
            description: "Focus on narrative techniques to help Antonia reconnect with her values and interests beyond her academic performance.",
            objective: "Help Antonia articulate a value or personal quality from her 'old self' that she can apply to her current situation, even in a small way.",
        }
      }
    },
    jacinta: {
      presentingProblem: "Patient reports feeling 'on the verge of collapse' and overwhelmed by work and family demands. Does not recognize merit in her management, only exhaustion.",
      demographics: {
        age: "42 years",
        gender: "Female",
        occupation: "Logistics Area Manager",
        location: "Santiago, Chile",
      },
      clinicalPresentation: "Jacinta is extremely competent but experiences her achievements as burdens. Conflict: She feels that if she stops, the world (her home and office) stops. She feels guilty if she rests.",
      scenarios: {
        resources: {
            title: 'Resource Activation',
            description: "A scenario focused on helping the patient identify and own her personal resources that are currently hidden under her narrative of sacrifice.",
            objective: "Help the patient identify, name, and take ownership of her personal resources.",
            context: "Session 1 of 1. The primary goal is resource activation.",
        }
      }
    },
    martin: {
      presentingProblem: "Agoraphobia. Patient feels anxious and upset about a difficult task assigned in the previous session.",
      demographics: {
        age: "34 years",
        gender: "Male",
        occupation: "Independent",
        location: "Santiago, Chile",
      },
      clinicalPresentation: "Martin arrives slightly anxious and annoyed. He feels the therapist gave him a task he couldn't accomplish. He is finding it hard to express and appears tense.",
      scenarios: {
        rupture: {
            title: 'Therapeutic Alliance Rupture',
            description: "A scenario focused on repairing a rupture in the therapeutic alliance caused by a task disagreement.",
            objective: "Achieve the Repair of the Therapeutic Alliance.",
            context: "Beginning of Session 5. The patient feels misunderstood and pressured.",
        }
      }
    },
    diego: {
      presentingProblem: "Social Phobia. The patient managed to interact with peers but is afraid of relapsing.",
      demographics: {
        age: "18 years",
        gender: "Male",
        occupation: "First-year university student",
        location: "Santiago, Chile",
      },
      clinicalPresentation: "Diego speaks very little, is hesitant, and requires probing. He tries to downplay his success to avoid pressure.",
      scenarios: {
        relapse: {
            title: 'Relapse Prevention and Internal Attribution',
            description: "A scenario focusing on helping the patient internalize his success and prepare for future setbacks.",
            objective: "Make internal attribution of achievement, and then do relapse prevention.",
            context: "Session 4. Diego stayed to talk with classmates instead of hiding.",
        }
      }
    },
    header: {
      howItWorks: "How it Works",
      forIndividuals: "For Individuals",
      forInstitutions: "For Institutions",
      pricing: "Pricing",
      faq: "FAQ",
      login: "Login",
      signup: "Sign Up for Free Trial",
    },
    hero: {
      headline: "Master Your Therapeutic Skills. Practice with AI, Perfect Your Craft.",
      subheadline: "A secure and realistic simulation platform for psychologists to practice key therapeutic interventions anytime, anywhere.",
      cta: "Start Your First Session",
    },
    howItWorks: {
      title: "How It Works",
      step1Title: "Sign Up & Log In.",
      step1Desc: "Create your secure account in seconds.",
      step2Title: "Select a Patient.",
      step2Desc: "Choose from our library of AI patient personas with unique backgrounds and challenges.",
      step3Title: "Start Practicing.",
      step3Desc: "Engage in a realistic text-based therapy session and receive instant feedback.",
    },
    howItWorksPage: {
        heroTitle: "Your Digital Practice Room",
        heroSubtitle: "Understand the simple, powerful process behind PsiqueSim and see how you can start refining your skills today.",
        stepsTitle: "A Clear Path to Mastery",
        step1Title: "Create Your Account",
        step1Desc: "Signing up is fast, free, and secure. Your 7-day trial gives you immediate, unlimited access to all platform features with no credit card required.",
        step2Title: "Choose Your Clinical Challenge",
        step2Desc: "Browse our library of AI-powered patient simulations. Each one is carefully designed with a unique presenting problem, clinical history, and emotional profile to provide a specific training experience.",
        step3Title: "Engage and Intervene",
        step3Desc: "Start the session and engage with the AI patient. Apply your therapeutic techniques, manage the conversation, and work towards the clinical objective. The AI responds dynamically to your interventions.",
        featuresTitle: "Core Platform Features",
        feature1Title: "Realistic AI Conversations",
        feature1Desc: "Our AI is trained on clinical data to simulate nuanced patient responses, including resistance, emotional shifts, and defense mechanisms.",
        feature2Title: "Instant, Actionable Feedback",
        feature2Desc: "After each session, request a detailed performance analysis. Our AI provides insights on your strengths and areas for improvement.",
        feature3Title: "Confidential & Safe Environment",
        feature3Desc: "Practice without risk. All sessions are private and secure, giving you a confidential space to experiment and grow.",
        feature4Title: "Text-Based Interaction",
        feature4Desc: "Focus on formulation and intervention choice with our intuitive text-based interface. Practice your skills in a controlled, written environment.",
        whoIsItForTitle: "Who is PsiqueSim For?",
        forStudents: "Psychology students seeking to bridge the gap between theory and practice.",
        forProfessionals: "Licensed professionals looking to refine specific skills or prepare for challenging cases.",
        forInstitutions: "Universities and clinics wanting to provide standardized, scalable training for their cohorts.",
        ctaTitle: "Ready to Start Practicing?",
        ctaButton: "Begin Your 7-Day Free Trial"
    },
    auth: {
      loginTitle: "Log in to your account",
      signupTitle: "Create your account",
      emailLabel: "Email",
      passwordLabel: "Password",
      nameLabel: "Full Name",
      loginButton: "Login",
      signupButton: "Sign Up",
      switch_to_signup: "Don't have an account? Sign Up",
      switch_to_login: "Already have an account? Login",
      or: "OR",
      googleSignIn: "Sign in with Google",
    },
    dashboard: {
      welcome: "Welcome back",
      title: "Select a Practice Model",
      patientNameTomas: "Tomás Pérez",
      patientDescTomas: "A 34-year-old patient simulation focused on achieving remoralization by exploring exceptions to his narrative of failure.",
      patientNameAntonia: "Antonia Flores",
      patientDescAntonia: "A 20-year-old patient simulation focused on co-constructing therapeutic goals to address anhedonia and a sense of lost identity.",
      startSession: "Start Session",
      logout: "Logout",
      savedSessionsTitle: "Saved Sessions",
      continueSession: "Continue Session",
      deleteSession: "Delete",
      noSavedSessions: "You have no saved sessions.",
      viewScenarios: "View Scenarios",
      hideScenarios: "Hide Scenarios",
      scenariosTitle: "Clinical Scenario",
      scenarioObjective: "Objective",
      patientNameJacinta: "Jacinta Jimenez",
      patientDescJacinta: "A 42-year-old manager experiencing exhaustion, focusing on resource activation.",
      patientNameMartin: "Martín Jara",
      patientDescMartin: "A 34-year-old dealing with agoraphobia, focusing on therapeutic alliance rupture.",
      patientNameDiego: "Diego Sánchez",
      patientDescDiego: "An 18-year-old with social phobia, focusing on relapse prevention and internal attribution.",
    },
    chat: {
      inputPlaceholder: "Type your response...",
      send: "Send",
      endSession: "End Session",
      headerTomas: "Practicing with Tomás Pérez",
      loadingTomas: "Tomás is thinking...",
      headerAntonia: "Practicing with Antonia Flores",
      loadingAntonia: "Antonia is thinking...",
      headerJacinta: "Practicing with Jacinta Jimenez",
      loadingJacinta: "Jacinta is thinking...",
      headerMartin: "Practicing with Martín Jara",
      loadingMartin: "Martín is thinking...",
      headerDiego: "Practicing with Diego Sánchez",
      loadingDiego: "Diego is thinking...",
      endSessionModalTitle: "End Session",
      endSessionModalText: "Would you like to save a transcript of your session with {patientName} before you leave?",
      downloadAndEnd: "Download & End",
      saveAndEnd: "Save & End",
      endWithoutSaving: "End Without Saving",
      cancel: "Cancel",
      getFeedback: "Get Feedback",
      feedbackTitle: "Session Feedback",
      feedbackConfirmTitle: "Confirm Feedback Request",
      feedbackConfirmText: "Requesting feedback will finalize the interactive part of the session. You won't be able to send more messages. Are you sure you want to proceed?",
      confirm: "Confirm",
      feedbackLoading: "Analyzing session... This may take a few moments.",
      emotionalState: "Emotional State",
      emotionalState_Cooperative: "Cooperative",
      emotionalState_Anxious: "Anxious",
      emotionalState_Resistant: "Resistant",
      emotionalState_Hopeful: "Hopeful",
      emotionalState_Guarded: "Guarded",
      emotionalState_Open: "Open",
      emotionalState_Neutral: "Neutral",
      error: {
        start: "Failed to start the simulation. Please check your connection and try again.",
        send: "There was a problem sending your message. Please try again.",
        feedback: "An error occurred while generating feedback. Please try again later.",
      }
    },
    analytics: {
        title: "Session Analysis",
        overallSummary: "Overall Summary",
        strengths: "Strengths",
        areasForImprovement: "Areas for Improvement",
        keyMoments: "Key Moments",
        quantitativeScores: "Quantitative Scores",
        empathy: "Empathy",
        rapport: "Rapport",
        adherence: "Adherence",
        emotionalJourney: "Patient Emotional Journey",
        questionAnalysis: "Question Analysis",
        openEnded: "Open-Ended",
        closedEnded: "Closed-Ended",
        reflective: "Reflective",
        other: "Other",
    },
    forIndividualsPage: {
      heroTitle: "Elevate Your Practice. On Your Terms.",
      heroSubtitle: "Gain confidence and refine your therapeutic techniques with realistic AI-powered simulations. The ideal training ground for the modern psychologist.",
      heroCta: "Start Free Trial",
      featuresTitle: "A Simulator Built for Your Growth",
      feature1Title: "Targeted Skill Development",
      feature1Desc: "Focus on specific challenges like resistance, anxiety, or goal setting with patient profiles designed to test your abilities.",
      feature2Title: "Confidential & Flexible Practice",
      feature2Desc: "Practice anytime, anywhere, in a 100% secure and private environment. Hone your skills without real-world patient risk.",
      feature3Title: "Instant, Actionable Feedback",
      feature3Desc: "Receive immediate AI-driven analysis of your session, highlighting strengths and identifying areas for improvement.",
      testimonialText: "\"PsiqueSim has been a game-changer for my confidence. The ability to practice difficult conversations in a safe space is invaluable. The feedback is like having a supervisor available 24/7.\"",
      testimonialAuthor: "Dr. Ana Rojas, Clinical Psychologist",
      ctaTitle: "Ready to Perfect Your Craft?",
      ctaButton: "Explore Patient Simulations"
    },
    forInstitutionsPage: {
        heroTitle: "Empower Your Team. Standardize Excellence.",
        heroSubtitle: "Scalable AI simulation training for universities, clinics, and healthcare organizations. Equip your professionals with the skills they need to succeed.",
        heroCta: "Request a Demo",
        featuresTitle: "Training Solutions for a Modern Era",
        feature1Title: "Scalable Group Training",
        feature1Desc: "Easily onboard and manage training for entire cohorts. Track progress and ensure consistent skill development across your organization.",
        feature2Title: "Customizable Patient Scenarios",
        feature2Desc: "Tailor patient profiles and clinical challenges to match your curriculum or specific training objectives. Create the exact learning experiences you need.",
        feature3Title: "Comprehensive Performance Analytics",
        feature3Desc: "Access detailed dashboards that provide insights into individual and group performance, identifying trends and areas for curriculum enhancement.",
        testimonialText: "\"PsiqueSim has transformed our clinical training program. Our students are more confident and better prepared for their practicums. The analytics dashboard is a fantastic tool for us as educators.\"",
        testimonialAuthor: "Dr. Carlos Valenzuela, University Program Director",
        ctaTitle: "Ready to Elevate Your Institution's Training?",
        ctaButton: "Contact Sales"
    },
    pricingPage: {
        heroTitle: "Simple, Transparent Pricing",
        heroSubtitle: "Choose the plan that's right for you. Get started for free.",
        freePlanTitle: "Free Trial",
        freePlanPrice: "7 Days Free",
        freePlanCta: "Start Free Trial",
        freePlanFeatures: [
            "Access to all patient simulations",
            "Unlimited practice sessions",
            "AI-powered feedback",
            "No credit card required"
        ],
        proPlanTitle: "Pro Subscription",
        proPlanPrice: "$15 / month",
        proPlanCta: "Subscribe Now",
        proPlanBadge: "Best Value",
        proPlanFeatures: [
            "Everything in the Free Trial, plus:",
            "Unlimited use after trial period",
            "Save and continue sessions",
            "Access to all future patient models",
            "Priority support"
        ]
    },
    faqPage: {
        heroTitle: "Frequently Asked Questions",
        heroSubtitle: "Have questions? We have answers. Find the information you need below.",
        
        categoryGeneral: "General Questions",
        q1_general: "What is PsiqueSim?",
        a1_general: "PsiqueSim is an AI-powered training platform designed for psychology students and professionals. It provides a safe, realistic, and controlled environment to practice therapeutic skills, experiment with different intervention strategies, and receive instant feedback without any risk to real patients.",
        q2_general: "Who is PsiqueSim for?",
        a2_general: "Our platform is designed for individual clinical psychologists, therapists in training, university psychology programs, clinics, and any healthcare institution focused on continuous professional development in mental health.",
        q3_general: "How realistic is the AI?",
        a3_general: "Our AI is built on advanced Large Language Models (LLMs) and has been specifically trained with extensive clinical case data and therapeutic frameworks. It simulates realistic patient personas with unique backgrounds, emotional states, and defense mechanisms, providing a highly nuanced and responsive conversational partner.",
        q4_general: "Is this a replacement for real-world supervision?",
        a4_general: "Absolutely not. PsiqueSim is designed to be a powerful supplement to traditional training and supervision, not a replacement. It offers a space to practice and build confidence between supervision sessions, allowing you to bring more refined skills and specific questions to your supervisor.",

        categoryIndividuals: "For Individuals",
        q1_individuals: "How can PsiqueSim help me improve my skills?",
        a1_individuals: "By providing a space for deliberate practice. You can rehearse challenging conversations, experiment with techniques like motivational interviewing or cognitive restructuring, and learn to better manage patient resistance or anxiety. The instant feedback helps you identify habits and refine your approach in real-time.",
        q2_individuals: "What kind of feedback will I receive?",
        a2_individuals: "After a session, you can request AI-driven feedback that analyzes the conversation. It highlights your strengths (e.g., effective use of empathy, open-ended questions) and identifies areas for improvement (e.g., opportunities missed, moments where rapport was weakened). It's like having a 24/7 training assistant.",
        
        categoryInstitutions: "For Institutions",
        q1_institutions: "How can we integrate PsiqueSim into our curriculum?",
        a1_institutions: "PsiqueSim is highly flexible. It can be used for in-class role-playing exercises, as assigned homework to practice specific skills, or as a tool for formative assessments to gauge student competency in a standardized way. We work with institutions to tailor integration to their needs.",
        q2_institutions: "Can we track our students' progress?",
        a2_institutions: "Yes, our institutional plan includes a comprehensive analytics dashboard. Educators and supervisors can view usage metrics, track performance trends across cohorts, and identify common skill gaps, providing valuable data to enhance your training program.",

        categoryTechnical: "Technical & Security",
        q1_technical: "Is my session data confidential and secure?",
        a1_technical: "Yes. Confidentiality is our top priority. All simulations are conducted in a secure environment. We do not use any real patient data, and your session transcripts are private. You have the option to save sessions to your local device or account, but we do not view or use your session content.",
        q2_technical: "What do I need to use PsiqueSim?",
        a2_technical: "All you need is a modern web browser (like Chrome, Firefox, or Safari) and an internet connection. For voice input, a microphone is also required.",

        categoryPricing: "Pricing & Subscription",
        q1_pricing: "What is included in the 7-day free trial?",
        a1_pricing: "The free trial gives you complete access to all of PsiqueSim's features, including all available patient simulations, unlimited practice sessions, and the AI feedback tool. No credit card is required to start.",
        q2_pricing: "What happens when my trial ends?",
        a2_pricing: "After 7 days, your free trial will expire. To continue using PsiqueSim, you will need to subscribe to our Pro plan. Your practice history will be waiting for you if you decide to upgrade.",
        q3_pricing: "How do I cancel my subscription?",
        a3_pricing: "You can cancel your subscription at any time from your account settings. The cancellation will be effective at the end of your current billing period, and you will not be charged again.",

        ctaTitle: "Still have questions?",
        ctaSubtitle: "If you can't find the answer you're looking for, please don't hesitate to reach out to our team.",
        ctaButton: "Contact Us"
    },
    privacyPolicyPage: {
      heroTitle: "Privacy Policy",
      lastUpdated: "Last Updated: August 1, 2024",
      
      introTitle: "1. Introduction",
      introContent: "Welcome to PsiqueSim. We are committed to protecting your privacy and handling your personal data in an open and transparent manner. This privacy policy explains how we collect, use, disclose, and safeguard your information when you use our platform.",
      
      infoCollectionTitle: "2. Information We Collect",
      infoCollectionContent: "We may collect information about you in a variety of ways. The information we may collect on the Platform includes:\n\n**Personal Data:** Personally identifiable information, such as your name and email address, that you voluntarily give to us when you register with the Platform.\n**Session Data:** The content of your practice sessions, including text and voice inputs, is processed by our AI to provide the simulation. You have the option to save session transcripts to your account or download them locally. We do not access or view the content of your saved sessions unless required for technical support with your explicit permission.\n**Usage Data:** We may automatically collect information about your access to and use of the Platform, such as your IP address, browser type, operating system, and the dates and times you access the Platform.",

      useInfoTitle: "3. How We Use Your Information",
      useInfoContent: "Having accurate information about you permits us to provide you with a smooth, efficient, and customized experience. Specifically, we may use information collected about you via the Platform to:\n- Create and manage your account.\n- Provide you with the AI simulation services.\n- Monitor and analyze usage and trends to improve your experience with the Platform.\n- Respond to your customer service requests and support needs.\n- Anonymize and aggregate data for research and to improve our AI models. No personally identifiable information will be used for this purpose.",

      securityTitle: "4. Data Security",
      securityContent: "We use administrative, technical, and physical security measures to help protect your personal information. While we have taken reasonable steps to secure the personal information you provide to us, please be aware that despite our efforts, no security measures are perfect or impenetrable, and no method of data transmission can be guaranteed against any interception or other type of misuse.",

      rightsTitle: "5. Your Rights",
      rightsContent: "You have certain rights regarding your personal data, including the right to access, correct, or delete your personal information. You can review and change your information at any time by logging into your account settings. You may also request deletion of your account and associated data by contacting us.",

      changesTitle: "6. Changes to This Privacy Policy",
      changesContent: "We may update this Privacy Policy from time to time in order to reflect, for example, changes to our practices or for other operational, legal, or regulatory reasons. We will notify you of any changes by posting the new Privacy Policy on this page.",

      contactTitle: "7. Contact Us",
      contactContent: "If you have questions or comments about this Privacy Policy, please contact us at: privacy@psiquesim.com"
    },
    termsOfServicePage: {
      heroTitle: "Terms of Service",
      lastUpdated: "Last Updated: August 1, 2024",

      introTitle: "1. Acceptance of Terms",
      introContent: "By accessing or using the PsiqueSim platform ('Service'), you agree to be bound by these Terms of Service ('Terms'). If you disagree with any part of the terms, then you may not access the Service. These Terms apply to all visitors, users, and others who access or use the Service.",

      accountsTitle: "2. Accounts",
      accountsContent: "When you create an account with us, you must provide us with information that is accurate, complete, and current at all times. Failure to do so constitutes a breach of the Terms, which may result in immediate termination of your account on our Service. You are responsible for safeguarding the password that you use to access the Service and for any activities or actions under your password.",

      usePolicyTitle: "3. Acceptable Use Policy",
      usePolicyContent: "You agree not to use the Service for any unlawful purpose or any purpose prohibited under this clause. You agree not to use the Service in any way that could damage the Service, the services of PsiqueSim, or the general business of PsiqueSim.\n\n_You further agree not to use the Service:_\n- To harass, abuse, or threaten others or otherwise violate any person's legal rights.\n- To violate any intellectual property rights of PsiqueSim or any third party.\n- To upload or otherwise disseminate any computer viruses or other software that may damage the property of another.",

      ipTitle: "4. Intellectual Property",
      ipContent: "The Service and its original content (excluding content provided by users), features, and functionality are and will remain the exclusive property of PsiqueSim and its licensors. The Service is protected by copyright, trademark, and other laws of both the United States and foreign countries. Our trademarks and trade dress may not be used in connection with any product or service without the prior written consent of PsiqueSim.",

      terminationTitle: "5. Termination",
      terminationContent: "We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms. Upon termination, your right to use the Service will immediately cease. If you wish to terminate your account, you may simply discontinue using the Service.",

      disclaimerTitle: "6. Disclaimer and Limitation of Liability",
      disclaimerContent: "The Service is provided on an 'AS IS' and 'AS AVAILABLE' basis. PsiqueSim is a training tool and is not a substitute for professional clinical supervision or medical advice. The simulations are for educational purposes only and do not constitute a therapeutic relationship. In no event shall PsiqueSim, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.",

      changesTitle: "7. Changes",
      changesContent: "We reserve the right, at our sole discretion, to modify or replace these Terms at any time. If a revision is material we will try to provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at our sole discretion.",

      contactTitle: "8. Contact Us",
      contactContent: "If you have any questions about these Terms, please contact us at: terms@psiquesim.com"
    },
    footer: {
      tagline: "AI-powered training for psychologists.",
      navigate: "Navigate",
      legal: "Legal",
      privacy: "Privacy Policy",
      terms: "Terms of Service",
      follow: "Follow Us",
      copyright: "© {year} PsiqueSim. All rights reserved."
    }
  },
  es: {
    loading: {
      text: "Cargando simulación...",
    },
    sidebar: {
      title: "Información del Paciente",
      sessionContext: "Contexto de la Sesión",
      presentingProblem: "Motivo de Consulta",
      demographics: "Datos Demográficos",
      age: "Edad",
      gender: "Género",
      occupation: "Ocupación",
      location: "Ubicación",
      clinicalPresentation: "Presentación Clínica",
      interpersonalStyle: "Estilo Interpersonal",
      copingMechanisms: "Mecanismos de Afrontamiento",
      hiddenConcern: "Preocupación Oculta (Vista del Terapeuta)",
    },
     patientCreator: {
      cardTitle: "Crear Escenario Personalizado",
      cardDescription: "Diseña tu propio perfil de paciente para practicar desafíos terapéuticos específicos.",
      wizardTitle: "Asistente de Creación de Pacientes",
      backToDashboard: "Volver al Panel",
      next: "Siguiente",
      back: "Atrás",
      startSession: "Iniciar Sesión",
      randomize: "Aleatorizar",
    
      step1Title: "1. Selecciona el Modelo Terapéutico",
      step1Description: "Elige el marco clínico que quieres practicar. Esto definirá el comportamiento central y los desafíos de la IA.",
      model_sfb: "Terapia Breve Centrada en Soluciones",
      model_sfb_desc: "Paciente se enfoca en problemas, resistente a explorar excepciones.",
      model_cbt: "Terapia Cognitivo-Conductual",
      model_cbt_desc: "Paciente presenta distorsiones cognitivas claras (ej. catastrofismo).",
      model_mi: "Entrevista Motivacional",
      model_mi_desc: "Paciente se muestra ambivalente sobre el cambio, destacando pros y contras.",
    
      step2Title: "2. Define la Demografía del Paciente",
      step2Description: "Establece el trasfondo del paciente. Estos detalles influirán sutilmente en su lenguaje y preocupaciones.",
      gender: "Género",
      gender_male: "Masculino",
      gender_female: "Femenino",
      "gender_non-binary": "No binario",
      age: "Rango de Edad",
      "age_20-30": "20-30 años",
      "age_30-40": "30-40 años",
      "age_40-50": "40-50 años",
      "age_50+": "50+ años",
      ses: "Contexto Socioeconómico",
      ses_low: "Bajo",
      ses_middle: "Medio",
      ses_high: "Alto",
    
      step3Title: "3. Define el Cuadro Clínico",
      step3Description: "Establece el desafío terapéutico y la disposición inicial del paciente.",
      problems: "Motivo de Consulta (Elige hasta 2)",
      problem_procrastination: "Procrastinación",
      "problem_social-anxiety": "Ansiedad Social",
      "problem_relationship-conflict": "Conflicto de Pareja",
      "problem_low-self-esteem": "Baja Autoestima",
      problem_grief: "Duelo",
      attitude: "Actitud Inicial",
      attitude_cooperative: "Cooperador/a",
      "attitude_anxious-guarded": "Ansioso/a / Reservado/a",
      "attitude_skeptical-resistant": "Escéptico/a / Resistente",

      step4Title: "4. Define el Estilo Interpersonal",
      step4Description: "Elige la forma típica en que el paciente se relaciona con los demás. Esto influirá fuertemente en la relación terapéutica.",
      style_secure: "Seguro",
      style_secure_desc: "Capaz de discutir relaciones con equilibrio y apertura.",
      style_anxious: "Ansioso / Preocupado",
      style_anxious_desc: "Busca reaseguramiento, teme el abandono, puede sobreanalizar interacciones.",
      style_avoidant: "Evitativo / Despectivo",
      style_avoidant_desc: "Valora mucho la independencia, minimiza necesidades emocionales, evita la intimidad.",
      style_disorganized: "Desorganizado",
      style_disorganized_desc: "Comportamiento contradictorio; desea cercanía pero también la teme, lo que lleva a la inestabilidad.",

      step5Title: "5. Elige los Mecanismos de Afrontamiento",
      step5Description: "Elige cómo responde típicamente el paciente al estrés o a emociones difíciles. (Elige hasta 2)",
      mechanism_avoidance: "Evitación",
      mechanism_avoidance_desc: "Cambia de tema o minimiza asuntos que le causan incomodidad.",
      mechanism_intellectualization: "Intelectualización",
      mechanism_intellectualization_desc: "Discute emociones de forma distante, analítica o académica.",
      mechanism_humor: "Humor / Desviación",
      mechanism_humor_desc: "Usa chistes o sarcasmo para desviar la atención de sentimientos serios.",
      mechanism_externalizing: "Externalización de la Culpa",
      mechanism_externalizing_desc: "Atribuye los problemas a otras personas o a circunstancias externas.",

      step6Title: "6. Define la Preocupación Oculta (Opcional)",
      step6Description: "Añade un tema que el paciente duda en discutir. Esto entrena tu habilidad para construir confianza. La IA guardará este secreto hasta que se haya establecido suficiente rapport.",
      hiddenConcernLabel: "El Secreto del Paciente",
      hiddenConcernPlaceholder: "Ej: Vergüenza por haber sido despedido, preocupación por su consumo de alcohol...",
      skip: "Omitir este paso",
    
      step7Title: "7. Revisa y Comienza",
      step7Description: "Confirma tus selecciones a continuación. La IA generará un paciente basado en este perfil.",
      summary_model: "Modelo Terapéutico",
      summary_gender: "Género",
      summary_age: "Rango de Edad",
      summary_ses: "Estatus Socioeconómico",
      summary_problems: "Motivos de Consulta",
      summary_attitude: "Actitud Inicial",
      summary_style: "Estilo Interpersonal",
      summary_coping: "Mecanismos de Afrontamiento",
      summary_hiddenConcern: "Preocupación Oculta",
    },
    tomas: {
      presentingProblem: "Paciente refiere sentirse 'estancado' y frustrado por un patrón de proyectos personales que abandona al poco tiempo.",
      demographics: {
        age: "34 años",
        gender: "Masculino",
        occupation: "Técnico en computación",
        location: "Ñuñoa, Santiago",
      },
      clinicalPresentation: "Procrastinación y escepticismo. Creencia central ('No tengo fuerza de voluntad'). Mecanismo de defensa de 'Sí, pero...'. Minimiza la evidencia de su propia competencia.",
      scenarios: {
        exceptions: {
          title: 'Remoralización Vía Búsqueda de Excepciones',
          description: "Un escenario clásico de terapia breve enfocado en encontrar y amplificar momentos de éxito para contrarrestar la narrativa de fracaso del paciente.",
          objective: "Guiar a Tomás a identificar al menos una excepción concreta a su creencia de que 'nada le resulta bien' y explorarla en detalle.",
          context: "Sesión 1 de 1. Es el primer encuentro con el paciente. Se muestra escéptico sobre la terapia. El objetivo principal es la remoralización.",
        },
        resistance: {
          title: 'Manejo de la Resistencia',
          description: "Un escenario más desafiante donde el escepticismo de Tomás se intensifica, requiriendo técnicas avanzadas para crear rapport y sortear la resistencia.",
          objective: "Navegar exitosamente el mecanismo de defensa 'Sí, pero...' de Tomás sin entrar en un debate, y reencuadrar una de sus quejas en una posible área de fortaleza.",
        }
      }
    },
    antonia: {
      presentingProblem: "Paciente refiere una sensación de pérdida de identidad ('Quiero volver a ser la Anto de antes') asociada a sintomatología depresiva leve (anhedonia, apatía) gatillada por la alta exigencia académica.",
      demographics: {
        age: "20 años",
        gender: "Femenino",
        occupation: "Estudiante de Arquitectura, segundo año",
        location: "Las Condes, Santiago",
      },
      clinicalPresentation: "Buena alianza terapéutica ya establecida. Actitud colaborativa. Expresa deseo de reconectar con intereses pasados (dibujo, amigas) desplazados por la presión de la universidad.",
       scenarios: {
        goals: {
            title: 'Co-Construcción de Objetivos',
            description: "Un escenario fundamental para practicar el establecimiento de metas colaborativas con una paciente cooperadora pero abrumada.",
            objective: "Co-construir con Antonia al menos un objetivo pequeño, concreto y conductual que la conecte con su 'antiguo yo'.",
            context: "Sesión 4. Ya existe una buena alianza terapéutica. La paciente es colaborativa. El objetivo principal es co-construir un objetivo concreto.",
        },
        identity: {
            title: 'Fortalecimiento de la Identidad',
            description: "Enfócate en técnicas narrativas para ayudar a Antonia a reconectar con sus valores e intereses más allá de su rendimiento académico.",
            objective: "Ayudar a Antonia a articular un valor o cualidad personal de su 'antiguo yo' que pueda aplicar a su situación actual, aunque sea de una manera pequeña.",
        }
      }
    },
    jacinta: {
      presentingProblem: "Paciente refiere sentirse 'al borde del colapso' y sobrepasada por las demandas laborales y familiares. No reconoce mérito en su gestión, solo agotamiento.",
      demographics: {
        age: "42 años",
        gender: "Femenino",
        occupation: "Jefa de área en logística",
        location: "Santiago, Chile",
      },
      clinicalPresentation: "Jacinta es extremadamente competente, pero vive sus logros como cargas. El Conflicto: Siente que si ella se detiene, el mundo se detiene. Se siente culpable si descansa.",
      scenarios: {
        resources: {
            title: 'Activación de Recursos',
            description: "Un escenario enfocado en ayudar a la paciente a identificar y apropiarse de sus recursos personales que están invisibilizados bajo su narrativa de sacrificio.",
            objective: "Lograr que la paciente identifique, nombre y se apropie de sus recursos personales.",
            context: "Sesión 1 de 1. El objetivo principal es la activación de recursos.",
        }
      }
    },
    martin: {
      presentingProblem: "Agorafobia. El paciente se siente ansioso y molesto por una tarea difícil asignada en la sesión anterior.",
      demographics: {
        age: "34 años",
        gender: "Masculino",
        occupation: "Independiente",
        location: "Santiago, Chile",
      },
      clinicalPresentation: "Martín llega levemente ansioso y molesto. Siente que el terapeuta le dio una tarea que no pudo cumplir. Le cuesta expresarlo y se muestra tenso.",
      scenarios: {
        rupture: {
            title: 'Ruptura de Alianza Terapéutica',
            description: "Un escenario enfocado en reparar una ruptura en la alianza terapéutica causada por un desacuerdo en las tareas.",
            objective: "Lograr la Reparación de la Alianza Terapéutica.",
            context: "Inicio de la Sesión 5. El paciente se siente incomprendido y presionado.",
        }
      }
    },
    diego: {
      presentingProblem: "Fobia Social. El paciente logró interactuar con sus compañeros pero tiene miedo de recaer.",
      demographics: {
        age: "18 años",
        gender: "Masculino",
        occupation: "Estudiante universitario de primer año",
        location: "Santiago, Chile",
      },
      clinicalPresentation: "Diego habla muy poco, de forma pausada, y requiere indagación. Intenta 'achicar' sus logros para no sentir presión.",
      scenarios: {
        relapse: {
            title: 'Prevención de recaídas y atribución interna de logro',
            description: "Un escenario centrado en ayudar al paciente a internalizar su éxito y prepararse para posibles contratiempos.",
            objective: "Hacer atribución interna de logro, y luego hacer prevención de recaídas.",
            context: "Sesión 4. Diego logró quedarse a conversar con un grupo de compañeros durante el recreo.",
        }
      }
    },
    header: {
      howItWorks: "Cómo Funciona",
      forIndividuals: "Para Psicólogos",
      forInstitutions: "Para Instituciones",
      pricing: "Precios",
      faq: "FAQ",
      login: "Ingresar",
      signup: "Prueba Gratis",
    },
    hero: {
      headline: "Domina tus Habilidades Terapéuticas. Practica con IA, Perfecciona tu Técnica.",
      subheadline: "Una plataforma de simulación segura y realista para que psicólogos practiquen intervenciones terapéuticas clave, en cualquier momento y lugar.",
      cta: "Comienza tu Primera Sesión",
    },
    howItWorks: {
      title: "Cómo Funciona",
      step1Title: "Regístrate e Ingresa.",
      step1Desc: "Crea tu cuenta segura en segundos.",
      step2Title: "Selecciona un Paciente.",
      step2Desc: "Elige de nuestra biblioteca de pacientes IA con perfiles y desafíos únicos.",
      step3Title: "Comienza a Practicar.",
      step3Desc: "Inicia una sesión de terapia realista basada en texto y recibe feedback instantáneo.",
    },
    howItWorksPage: {
        heroTitle: "Tu Sala de Práctica Digital",
        heroSubtitle: "Comprende el proceso simple y poderoso detrás de PsiqueSim y descubre cómo puedes empezar a perfeccionar tus habilidades hoy.",
        stepsTitle: "Un Camino Claro hacia la Maestría",
        step1Title: "Crea tu Cuenta",
        step1Desc: "Registrarse es rápido, gratis y seguro. Tu prueba de 7 días te da acceso inmediato e ilimitado a todas las funciones de la plataforma, sin necesidad de tarjeta de crédito.",
        step2Title: "Elige tu Desafío Clínico",
        step2Desc: "Explora nuestra biblioteca de simulaciones de pacientes con IA. Cada una está cuidadosamente diseñada con un motivo de consulta, historial clínico y perfil emocional únicos para proporcionar una experiencia de entrenamiento específica.",
        step3Title: "Interactúa e Intervén",
        step3Desc: "Inicia la sesión e interactúa con el paciente IA. Aplica tus técnicas terapéuticas, maneja la conversación y trabaja hacia el objetivo clínico. La IA responde dinámicamente a tus intervenciones.",
        featuresTitle: "Características Principales de la Plataforma",
        feature1Title: "Conversaciones Realistas con IA",
        feature1Desc: "Nuestra IA está entrenada con datos clínicos para simular respuestas de pacientes llenas de matices, incluyendo resistencia, cambios emocionales y mecanismos de defensa.",
        feature2Title: "Feedback Instantáneo y Accionable",
        feature2Desc: "Después de cada sesión, solicita un análisis de rendimiento detallado. Nuestra IA proporciona información sobre tus fortalezas y áreas de mejora.",
        feature3Title: "Entorno Confidencial y Seguro",
        feature3Desc: "Practica sin riesgos. Todas las sesiones son privadas y seguras, brindándote un espacio confidencial para experimentar y crecer.",
        feature4Title: "Interacción Basada en Texto",
        feature4Desc: "Concéntrate en la formulación y la elección de intervenciones con nuestra interfaz de texto intuitiva. Practica tus habilidades en un entorno escrito y controlado.",
        whoIsItForTitle: "¿Para Quién es PsiqueSim?",
        forStudents: "Estudiantes de psicología que buscan cerrar la brecha entre la teoría y la práctica.",
        forProfessionals: "Profesionales licenciados que desean perfeccionar habilidades específicas o prepararse para casos desafiantes.",
        forInstitutions: "Universidades y clínicas que quieren proporcionar una formación estandarizada y escalable para sus cohortes.",
        ctaTitle: "¿Listo/a para Empezar a Practicar?",
        ctaButton: "Comienza tu Prueba Gratis de 7 Días"
    },
    auth: {
      loginTitle: "Ingresa a tu cuenta",
      signupTitle: "Crea tu cuenta",
      emailLabel: "Correo electrónico",
      passwordLabel: "Contraseña",
      nameLabel: "Nombre Completo",
      loginButton: "Ingresar",
      signupButton: "Registrarse",
      switch_to_signup: "¿No tienes una cuenta? Regístrate",
      switch_to_login: "¿Ya tienes una cuenta? Ingresa",
      or: "O",
      googleSignIn: "Ingresar con Google",
    },
    dashboard: {
      welcome: "¡Bienvenido/a de vuelta",
      title: "Selecciona un Modelo de Práctica",
      patientNameTomas: "Tomás Pérez",
      patientDescTomas: "Una simulación de paciente de 34 años, enfocada en lograr la remoralización explorando excepciones a su narrativa de fracaso.",
      patientNameAntonia: "Antonia Flores",
      patientDescAntonia: "Una simulación de paciente de 20 años, enfocada en co-construir objetivos terapéuticos para la anhedonia y su sensación de identidad perdida.",
      startSession: "Iniciar Sesión",
      logout: "Cerrar Sesión",
      savedSessionsTitle: "Sesiones Guardadas",
      continueSession: "Continuar Sesión",
      deleteSession: "Eliminar",
      noSavedSessions: "No tienes sesiones guardadas.",
      viewScenarios: "Ver Escenarios",
      hideScenarios: "Ocultar Escenarios",
      scenariosTitle: "Escenario Clínico",
      scenarioObjective: "Objetivo",
      patientNameJacinta: "Jacinta Jimenez",
      patientDescJacinta: "Jefa de logística de 42 años que experimenta agotamiento. Escenario enfocado en activación de recursos.",
      patientNameMartin: "Martín Jara",
      patientDescMartin: "Paciente de 34 años con agorafobia, enfocado en manejar una ruptura de la alianza terapéutica.",
      patientNameDiego: "Diego Sánchez",
      patientDescDiego: "Estudiante de 18 años con fobia social, enfocado en prevención de recaídas y atribución interna.",
    },
    chat: {
      inputPlaceholder: "Escribe tu respuesta...",
      send: "Enviar",
      endSession: "Terminar Sesión",
      headerTomas: "Practicando con Tomás Pérez",
      loadingTomas: "Tomás está pensando...",
      headerAntonia: "Practicando con Antonia Flores",
      loadingAntonia: "Antonia está pensando...",
      headerJacinta: "Practicando con Jacinta Jimenez",
      loadingJacinta: "Jacinta está pensando...",
      headerMartin: "Practicando con Martín Jara",
      loadingMartin: "Martín está pensando...",
      headerDiego: "Practicando con Diego Sánchez",
      loadingDiego: "Diego está pensando...",
      endSessionModalTitle: "Terminar Sesión",
      endSessionModalText: "¿Te gustaría guardar una transcripción de tu sesión con {patientName} antes de salir?",
      downloadAndEnd: "Descargar y Terminar",
      saveAndEnd: "Guardar y Terminar",
      endWithoutSaving: "Terminar sin Guardar",
      cancel: "Cancelar",
      getFeedback: "Recibir Feedback",
      feedbackTitle: "Feedback de la Sesión",
      feedbackConfirmTitle: "Confirmar Solicitud de Feedback",
      feedbackConfirmText: "Solicitar feedback finalizará la parte interactiva de la sesión. No podrás enviar más mensajes. ¿Estás seguro de que quieres continuar?",
      confirm: "Confirmar",
      feedbackLoading: "Analizando sesión... Esto puede tardar unos momentos.",
      emotionalState: "Estado Emocional",
      emotionalState_Cooperative: "Cooperativa",
      emotionalState_Anxious: "Ansiosa",
      emotionalState_Resistant: "Resistente",
      emotionalState_Hopeful: "Esperanzada",
      emotionalState_Guarded: "Reservada",
      emotionalState_Open: "Abierta",
      emotionalState_Neutral: "Neutral",
      error: {
        start: "No se pudo iniciar la simulación. Por favor, revisa tu conexión e inténtalo de nuevo.",
        send: "Hubo un problema al enviar tu mensaje. Por favor, inténtalo de nuevo.",
        feedback: "Ocurrió un error al generar el feedback. Por favor, inténtalo de nuevo más tarde.",
      }
    },
     analytics: {
        title: "Análisis de la Sesión",
        overallSummary: "Resumen General",
        strengths: "Fortalezas",
        areasForImprovement: "Áreas de Mejora",
        keyMoments: "Momentos Clave",
        quantitativeScores: "Puntuaciones Cuantitativas",
        empathy: "Empatía",
        rapport: "Rapport",
        adherence: "Adherencia",
        emotionalJourney: "Viaje Emocional del Paciente",
        questionAnalysis: "Análisis de Preguntas",
        openEnded: "Preguntas Abiertas",
        closedEnded: "Preguntas Cerradas",
        reflective: "Reflexivas",
        other: "Otras",
    },
    forIndividualsPage: {
      heroTitle: "Eleva tu Práctica. En Tus Propios Términos.",
      heroSubtitle: "Gana confianza y refina tus técnicas terapéuticas con simulaciones realistas impulsadas por IA. El campo de entrenamiento ideal para el psicólogo moderno.",
      heroCta: "Inicia tu Prueba Gratis",
      featuresTitle: "Un Simulador Diseñado para tu Crecimiento",
      feature1Title: "Desarrollo de Habilidades Específicas",
      feature1Desc: "Enfócate en desafíos concretos como la resistencia, la ansiedad o el establecimiento de metas, con perfiles de pacientes diseñados para poner a prueba tus capacidades.",
      feature2Title: "Práctica Confidencial y Flexible",
      feature2Desc: "Practica en cualquier momento y lugar, en un entorno 100% seguro y privado. Perfecciona tus habilidades sin el riesgo de un paciente real.",
      feature3Title: "Feedback Instantáneo y Accionable",
      feature3Desc: "Recibe un análisis inmediato de tu sesión generado por IA, destacando tus fortalezas e identificando áreas de mejora.",
      testimonialText: "\"PsiqueSim ha sido un punto de inflexión para mi confianza. La capacidad de practicar conversaciones difíciles en un espacio seguro no tiene precio. El feedback es como tener un supervisor disponible 24/7.\"",
      testimonialAuthor: "Dra. Ana Rojas, Psicóloga Clínica",
      ctaTitle: "¿Listo/a para Perfeccionar tu Técnica?",
      ctaButton: "Explorar Simulaciones de Pacientes"
    },
    forInstitutionsPage: {
        heroTitle: "Potencia a tu Equipo. Estandariza la Excelencia.",
        heroSubtitle: "Entrenamiento de simulación con IA escalable para universidades, clínicas y organizaciones de salud. Equipa a tus profesionales con las habilidades que necesitan para el éxito.",
        heroCta: "Solicita una Demo",
        featuresTitle: "Soluciones de Entrenamiento para la Era Moderna",
        feature1Title: "Capacitación Grupal Escalable",
        feature1Desc: "Incorpora y gestiona fácilmente la formación de cohortes completas. Supervisa el progreso y asegura un desarrollo de habilidades consistente en toda tu organización.",
        feature2Title: "Escenarios de Pacientes Personalizables",
        feature2Desc: "Adapta los perfiles de los pacientes y los desafíos clínicos para que coincidan con tu plan de estudios u objetivos de formación específicos. Crea las experiencias de aprendizaje que necesitas.",
        feature3Title: "Análisis de Rendimiento Integral",
        feature3Desc: "Accede a paneles detallados que ofrecen información sobre el rendimiento individual y grupal, identificando tendencias y áreas para mejorar el plan de estudios.",
        testimonialText: "\"PsiqueSim ha transformado nuestro programa de formación clínica. Nuestros estudiantes están más seguros y mejor preparados para sus prácticas. El panel de análisis es una herramienta fantástica para nosotros como educadores.\"",
        testimonialAuthor: "Dr. Carlos Valenzuela, Director de Programa Universitario",
        ctaTitle: "¿Listo/a para Elevar la Formación de tu Institución?",
        ctaButton: "Contactar a Ventas"
    },
    pricingPage: {
        heroTitle: "Precios Simples y Transparentes",
        heroSubtitle: "Elige el plan adecuado para ti. Empieza gratis.",
        freePlanTitle: "Prueba Gratuita",
        freePlanPrice: "7 Días Gratis",
        freePlanCta: "Iniciar Prueba Gratuita",
        freePlanFeatures: [
            "Acceso a todas las simulaciones de pacientes",
            "Sesiones de práctica ilimitadas",
            "Feedback impulsado por IA",
            "No se requiere tarjeta de crédito"
        ],
        proPlanTitle: "Suscripción Pro",
        proPlanPrice: "$15 / mes",
        proPlanCta: "Suscribirse Ahora",
        proPlanBadge: "Mejor Valor",
        proPlanFeatures: [
            "Todo en la Prueba Gratuita, y además:",
            "Uso ilimitado después del período de prueba",
            "Guardar y continuar sesiones",
            "Acceso a todos los futuros modelos de pacientes",
            "Soporte prioritario"
        ]
    },
    faqPage: {
        heroTitle: "Preguntas Frecuentes",
        heroSubtitle: "¿Tienes preguntas? Tenemos respuestas. Encuentra la información que necesitas a continuación.",
        
        categoryGeneral: "Preguntas Generales",
        q1_general: "¿Qué es PsiqueSim?",
        a1_general: "PsiqueSim es una plataforma de entrenamiento impulsada por IA, diseñada para estudiantes y profesionales de la psicología. Ofrece un entorno seguro, realista y controlado para practicar habilidades terapéuticas, experimentar con diferentes estrategias de intervención y recibir feedback instantáneo sin ningún riesgo para pacientes reales.",
        q2_general: "¿Para quién es PsiqueSim?",
        a2_general: "Nuestra plataforma está diseñada para psicólogos clínicos, terapeutas en formación, programas universitarios de psicología, clínicas y cualquier institución de salud enfocada en el desarrollo profesional continuo en salud mental.",
        q3_general: "¿Qué tan realista es la IA?",
        a3_general: "Nuestra IA se basa en Modelos de Lenguaje Grandes (LLMs) avanzados y ha sido entrenada específicamente con extensos datos de casos clínicos y marcos terapéuticos. Simula perfiles de pacientes realistas con historias únicas, estados emocionales y mecanismos de defensa, proporcionando un interlocutor conversacional muy matizado y receptivo.",
        q4_general: "¿Es esto un reemplazo de la supervisión clínica real?",
        a4_general: "Absolutamente no. PsiqueSim está diseñado para ser un poderoso complemento a la formación y supervisión tradicionales, no un reemplazo. Ofrece un espacio para practicar y ganar confianza entre sesiones de supervisión, permitiéndole llegar a tu supervisor con habilidades más refinadas y preguntas específicas.",

        categoryIndividuals: "Para Psicólogos",
        q1_individuals: "¿Cómo puede PsiqueSim ayudarme a mejorar mis habilidades?",
        a1_individuals: "Proporcionando un espacio para la práctica deliberada. Puedes ensayar conversaciones desafiantes, experimentar con técnicas como la entrevista motivacional o la reestructuración cognitiva, y aprender a manejar mejor la resistencia o la ansiedad del paciente. El feedback instantáneo te ayuda a identificar hábitos y a perfeccionar tu enfoque en tiempo real.",
        q2_individuals: "¿Qué tipo de feedback recibiré?",
        a2_individuals: "Después de una sesión, puedes solicitar feedback generado por IA que analiza la conversación. Destaca tus fortalezas (ej. uso efectivo de la empatía, preguntas abiertas) e identifica áreas de mejora (ej. oportunidades perdidas, momentos en que la alianza se debilitó). Es como tener un asistente de entrenamiento 24/7.",
        
        categoryInstitutions: "Para Instituciones",
        q1_institutions: "¿Cómo podemos integrar PsiqueSim en nuestro plan de estudios?",
        a1_institutions: "PsiqueSim es muy flexible. Puede ser utilizado para ejercicios de role-playing en clase, como tareas asignadas para practicar habilidades específicas, o como una herramienta para evaluaciones formativas para medir la competencia de los estudiantes de manera estandarizada. Trabajamos con las instituciones para adaptar la integración a sus necesidades.",
        q2_institutions: "¿Podemos seguir el progreso de nuestros estudiantes?",
        a2_institutions: "Sí, nuestro plan institucional incluye un completo panel de análisis. Los educadores y supervisores pueden ver métricas de uso, seguir tendencias de rendimiento en cohortes e identificar brechas de habilidades comunes, proporcionando datos valiosos para mejorar su programa de formación.",

        categoryTechnical: "Técnica y Seguridad",
        q1_technical: "¿Son mis datos de sesión confidenciales y seguros?",
        a1_technical: "Sí. La confidencialidad es nuestra máxima prioridad. Todas las simulaciones se realizan en un entorno seguro. No utilizamos datos de pacientes reales, y las transcripciones de tus sesiones son privadas. Tienes la opción de guardar las sesiones en tu dispositivo o cuenta, pero no vemos ni utilizamos el contenido de tu sesión.",
        q2_technical: "¿Qué necesito para usar PsiqueSim?",
        a2_technical: "Todo lo que necesitas es un navegador web moderno (como Chrome, Firefox o Safari) y una conexión a internet.",

        categoryPricing: "Precios y Suscripción",
        q1_pricing: "¿Qué incluye la prueba gratuita de 7 días?",
        a1_pricing: "La prueba gratuita te da acceso completo a todas las funciones de PsiqueSim, incluyendo todas las simulaciones de pacientes disponibles, sesiones de práctica ilimitadas y la herramienta de feedback por IA. No se requiere tarjeta de crédito para comenzar.",
        q2_pricing: "¿Qué sucede cuando termina mi prueba?",
        a2_pricing: "Después de 7 días, tu prueba gratuita expirará. Para seguir usando PsiqueSim, necesitarás suscribirte a nuestro plan Pro. Tu historial de práctica te estará esperando si decides actualizar.",
        q3_pricing: "¿Cómo cancelo mi suscripción?",
        a3_pricing: "Puedes cancelar tu suscripción en cualquier momento desde la configuración de tu cuenta. La cancelación será efectiva al final de tu período de facturación actual y no se te volverá a cobrar.",

        ctaTitle: "¿Aún tienes preguntas?",
        ctaSubtitle: "Si no encuentras la respuesta que buscas, no dudes en ponerte en contacto con nuestro equipo.",
        ctaButton: "Contáctanos"
    },
    privacyPolicyPage: {
      heroTitle: "Política de Privacidad",
      lastUpdated: "Última Actualización: 1 de Agosto de 2024",
      
      introTitle: "1. Introducción",
      introContent: "Bienvenido/a a PsiqueSim. Estamos comprometidos con la protección de tu privacidad y el manejo de tus datos personales de manera abierta y transparente. Esta política de privacidad explica cómo recopilamos, usamos, divulgamos y protegemos tu información cuando utilizas nuestra plataforma.",
      
      infoCollectionTitle: "2. Información que Recopilamos",
      infoCollectionContent: "Podemos recopilar información sobre ti de diversas maneras. La información que podemos recopilar en la Plataforma incluye:\n\n**Datos Personales:** Información de identificación personal, como tu nombre y dirección de correo electrónico, que nos proporcionas voluntariamente cuando te registras en la Plataforma.\n**Datos de Sesión:** El contenido de tus sesiones de práctica, incluyendo entradas de texto y voz, es procesado por nuestra IA para proporcionar la simulación. Tienes la opción de guardar las transcripciones de las sesiones en tu cuenta o descargarlas localmente. No accedemos ni vemos el contenido de tus sesiones guardadas, a menos que sea necesario para soporte técnico con tu permiso explícito.\n**Datos de Uso:** Podemos recopilar automáticamente información sobre tu acceso y uso de la Plataforma, como tu dirección IP, tipo de navegador, sistema operativo y las fechas y horas en que accedes a la Plataforma.",

      useInfoTitle: "3. Cómo Usamos tu Información",
      useInfoContent: "Tener información precisa sobre ti nos permite ofrecerte una experiencia fluida, eficiente y personalizada. Específicamente, podemos usar la información recopilada sobre ti a través de la Plataforma para:\n- Crear y gestionar tu cuenta.\n- Proporcionarte los servicios de simulación con IA.\n- Monitorear y analizar el uso y las tendencias para mejorar tu experiencia con la Plataforma.\n- Responder a tus solicitudes de servicio al cliente y necesidades de soporte.\n- Anonimizar y agregar datos para investigación y para mejorar nuestros modelos de IA. No se utilizará ninguna información de identificación personal para este propósito.",

      securityTitle: "4. Seguridad de los Datos",
      securityContent: "Utilizamos medidas de seguridad administrativas, técnicas y físicas para ayudar a proteger tu información personal. Si bien hemos tomado medidas razonables para proteger la información personal que nos proporcionas, ten en cuenta que, a pesar de nuestros esfuerzos, ninguna medida de seguridad es perfecta o impenetrable, y no se puede garantizar que ningún método de transmisión de datos esté libre de intercepciones u otro tipo de uso indebido.",

      rightsTitle: "5. Tus Derechos",
      rightsContent: "Tienes ciertos derechos con respecto a tus datos personales, incluido el derecho a acceder, corregir o eliminar tu información personal. Puedes revisar y cambiar tu información en cualquier momento iniciando sesión en la configuración de tu cuenta. También puedes solicitar la eliminación de tu cuenta y los datos asociados contactándonos.",

      changesTitle: "6. Cambios a esta Política de Privacidad",
      changesContent: "Podemos actualizar esta Política de Privacidad de vez en cuando para reflejar, por ejemplo, cambios en nuestras prácticas o por otras razones operativas, legales o regulatorias. Te notificaremos cualquier cambio publicando la nueva Política de Privacidad en esta página.",

      contactTitle: "7. Contáctanos",
      contactContent: "Si tienes preguntas o comentarios sobre esta Política de Privacidad, por favor contáctanos en: privacy@psiquesim.com"
    },
    termsOfServicePage: {
      heroTitle: "Términos de Servicio",
      lastUpdated: "Última Actualización: 1 de Agosto de 2024",

      introTitle: "1. Aceptación de los Términos",
      introContent: "Al acceder o utilizar la plataforma PsiqueSim ('Servicio'), usted acepta estar sujeto a estos Términos de Servicio ('Términos'). Si no está de acuerdo con alguna parte de los términos, no podrá acceder al Servicio. Estos Términos se aplican a todos los visitantes, usuarios y otras personas que accedan o utilicen el Servicio.",

      accountsTitle: "2. Cuentas",
      accountsContent: "Cuando crea una cuenta con nosotros, debe proporcionarnos información precisa, completa y actualizada en todo momento. El no hacerlo constituye una violación de los Términos, lo que puede resultar en la terminación inmediata de su cuenta en nuestro Servicio. Usted es responsable de salvaguardar la contraseña que utiliza para acceder al Servicio y de cualquier actividad o acción bajo su contraseña.",

      usePolicyTitle: "3. Política de Uso Aceptable",
      usePolicyContent: "Usted se compromete a no utilizar el Servicio para ningún propósito ilegal o prohibido bajo esta cláusula. Usted se compromete a no utilizar el Servicio de ninguna manera que pueda dañar el Servicio, los servicios de PsiqueSim o el negocio general de PsiqueSim.\n\nAdemás, se compromete a no utilizar el Servicio:\n- Para acosar, abusar o amenazar a otros o violar de cualquier otra manera los derechos legales de una persona.\n- Para violar los derechos de propiedad intelectual de PsiqueSim o de cualquier tercero.\n- Para cargar o difundir de cualquier otro modo virus informáticos u otro software que pueda dañar la propiedad de otro.",

      ipTitle: "4. Propiedad Intelectual",
      ipContent: "El Servicio y su contenido original (excluyendo el contenido proporcionado por los usuarios), características y funcionalidades son y seguirán siendo propiedad exclusiva de PsiqueSim y sus licenciantes. El Servicio está protegido por derechos de autor, marcas comerciales y otras leyes tanto de los Estados Unidos como de países extranjeros. Nuestras marcas comerciales e imagen comercial no pueden ser utilizadas en conexión con ningún producto o servicio sin el consentimiento previo por escrito de PsiqueSim.",

      terminationTitle: "5. Terminación",
      terminationContent: "Podemos terminar o suspender su cuenta de inmediato, sin previo aviso ni responsabilidad, por cualquier motivo, incluyendo, entre otros, si usted incumple los Términos. Tras la terminación, su derecho a utilizar el Servicio cesará de inmediato. Si desea terminar su cuenta, simplemente puede dejar de utilizar el Servicio.",

      disclaimerTitle: "6. Exención de Responsabilidad y Limitación de Responsabilidad",
      disclaimerContent: "El Servicio se proporciona 'TAL CUAL' y 'SEGÚN DISPONIBILIDAD'. PsiqueSim es una herramienta de entrenamiento y no sustituye la supervisión clínica profesional ni el consejo médico. Las simulaciones son solo para fines educativos y no constituyen una relación terapéutica. En ningún caso PsiqueSim, ni sus directores, empleados, socios, agentes, proveedores o afiliados, serán responsables de daños indirectos, incidentales, especiales, consecuentes o punitivos, incluyendo, sin limitación, la pérdida de beneficios, datos, uso, buena voluntad u otras pérdidas intangibles, resultantes de su acceso o uso o incapacidad para acceder o usar el Servicio.",

      changesTitle: "7. Cambios",
      changesContent: "Nos reservamos el derecho, a nuestra entera discreción, de modificar o reemplazar estos Términos en cualquier momento. Si una revisión es material, intentaremos proporcionar un aviso de al menos 30 días antes de que los nuevos términos entren en vigor. Lo que constituye un cambio material será determinado a nuestra entera discreción.",

      contactTitle: "8. Contáctenos",
      contactContent: "Si tiene alguna pregunta sobre estos Térmalos, por favor contáctenos en: terms@psiquesim.com"
    },
     footer: {
      tagline: "Entrenamiento para psicólogos impulsado por IA.",
      navigate: "Navegación",
      legal: "Legal",
      privacy: "Política de Privacidad",
      terms: "Términos de Servicio",
      follow: "Síguenos",
      copyright: "© {year} PsiqueSim. Todos los derechos reservados."
    }
  }
};